### ISSUE TITLE
Exceptions control

### ISSUE THREAD

**Issue by vladyslav-fenchak** [Clariteia/minos_microservice_saga#1]
Control multiple exceptions and extend from minos_microservice_common. Example:
`try:
    do_something()
except MinosException:
    rollback()
except SocketTimeout:
    no_blocking()`

**Comment by andrea-mucci** [comment]
Hi

I guess the best in terms to manage the Exceptions is to extend the MinosException with a custom exception like MinosSagaException

The MinosException base class is present in the Minos_microservice_common package

```python
class MinosSagaException(MinosException): pass
```

this Exception class accept a message as well:

```python
...
raise MinosSagaException("Minos Saga: the parameter is not valid")
```

the text format must be 

* the name of the Package, in that case Minos Saga
* a separator like ":"
* the text with a detailed Exception descritption
